version: "3.9"

volumes:
  pg-data:

services:
  app:
    build: .
    container_name: app
    image: app
    ports:
      - "8085:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:17.0
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "bhs"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "bhs"
    ports:
      - "5432:5432"